### ISSUE TITLE
erro ao construir o projeto

### ISSUE THREAD

**Issue by alexpseletr** [crossteam/pitangus#14]
1) tentei os comandos do install e recebi os retornos abaixo....

2) Porque de criar um arquivo de instalação todo em ingles (embora seja a linguagem padrao de programação) para um aplicativo de regras de tributação unicamente brasileiro (a menos que esse nao seja um objetivo futuro do projeto)...sugestao traduzir para portugues , se eu conseguir iniciar o uso do projeto posso tentar auxiliar nos fontes... 

3) achei bem interessante esse projeto pelo que propoe e o tamanho dos fontes se funcionar nota 10...

$ cd '/pitangus-master' 
$ autoconf
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:13: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:35: error: possibly undefined macro: AM_ENABLE_SHARED
configure.ac:36: error: possibly undefined macro: AC_ENABLE_SHARED
[alex@notealex pitangus-master]$ ./configure
./configure: line 2140: syntax error near unexpected token `pitangus,'
./configure: line 2140: `AM_INIT_AUTOMAKE(pitangus, 2.6)'
$ make
make: *** Nenhum alvo indicado e nenhum arquivo make encontrado.  Pare.
$

**Comment by silvioprog** [comment]
Olá @alexpseletr .

No momento estamos fazendo uma faxina geral para juntar todos os projetos em um só, daí ainda há instabilidade no building. E por falar em building, estive tento vários problemas com autotools em outras bibliotecas que acompanho e mantenho (inclusive algumas GNU) e tenho visto programadores mesmo experientes comentar que autotools é uma dificuldade terrível para fazer coisas simples, então fiquei de ver com o @pablogallardo sobre adotar CMake, por ser mais simples, direto e mais utilizado em bibliotecas mais modernas, tanto C quanto C++. Basta um "mkdir build && cd build && cmake ..." e tudo resolvido, sem mencionar que CMake é o sistema de building padrão na maioria das IDEs C/C++ (CLion, CodeBlocks, CodeLite, Android Studio (que agora suporta C/C++), Eclipse, NetBeans etc.).

Sobre alguns textos em inglês eles podem ser adaptados para o português tranquilamente no futuro, porém nossa prioridade agora é fazer a biblioteca voltar funcionar. Demos uma pausa no projeto devido um pouco de falta de incentivo, mas não abandonamos ele. :-) 

Obrigado pelo elogio. Ela vai funcionar, pois hoje nos falta uma biblioteca pequena ANSI C que realmente funcione, já que a maioria dos projetos de NF-e hoje são baseados em linguagens de alto nível não portáveis para as demais linguagens e não compiláveis para sistemas embarcados (ARM).

**Comment by pablogallardo** [comment]
Oi @alexpseletr!

Obrigado pelo interesse no projeto. Por favor, tenta o seguinte procedimento.

```shell
$ autoreconf --install
$ ./configure
$ make
```
É muito importante ter a última versão de xmlsec1 (recomendo compilar desde o código fonte baixado desde o site oficial do [projeto](https://www.aleksey.com/xmlsec/download.html).

Fique à vontade para fazer observações e sugestões de melhoria. O projeto chegou já a emitir notas em homologação. Temos que implementar a versão da NF 4.0. Na verdade, o projeto está atualmente em pausa por falta de tempo mas é importante que os usuários façam avaliações para que, quando retomemos este projeto, possamos saber em que podemos melhorá-lo.

**Comment by pablogallardo** [comment]
PS. Para a documentação de instalação em portugués veja https://github.com/pablogallardo/livrenfe arquivo README. Nosso próximo passo é colocar esse documento neste repositório.

**Comment by alexpseletr** [comment]
com a dica que deu funcionou , problemas de funcionamento relatados no outro topico

obrigado

**Comment by pablogallardo** [comment]
De nada :)
